<?php
// VC-1 Computer System
// Copyright (C) 2023 Appledog Hu
//
// SPDX-License-Identifier: GPL-2.0-only WITH VC-1-runtime-exception
// See LICENSE file for details.
//

// hitcount.php
// First discover total hits and second, user hits,
// and print them as a JSON file.
// Takes key as a post or get variable so we can differentiate between pages.
// Generated by ChatGPT 3.5 and reviewed by Appledog.

// Function to read and update hit count
function updateHitCount($file)
{
    $count = 0;

    if (file_exists($file)) {
        // Read the current count from the file
        $count = (int)file_get_contents($file);

    }

    // Increment the count
    $count++;

    // Write the updated count back to the file
    file_put_contents($file, $count);

    return $count;
}


// Function to update user's hit count
function updateUserHitCount($file, $key)
{
    $userHits = [];

    if (file_exists($file)) {
        // Read the current user hits from the file
        $userHits = json_decode(file_get_contents($file), true);
    }

    // Increment the user's count or initialize it to 1 if not present
    $userHits[$key] = isset($userHits[$key]) ? $userHits[$key] + 1 : 1;

    // Write the updated user hits back to the file
    file_put_contents($file, json_encode($userHits));

    return $userHits[$key];
}

// Determine the key from POST or GET variable
$key = isset($_REQUEST['key']) ? $_REQUEST['key'] : '';

if (empty($key)) {
    // If 'key' is not provided, return an error message
    $response = ['error' => 'Key not provided'];
} else {
    // File to store hit count
    $hitCountFile = 'hitcounter/hitcount_' . $key . '.txt';

    // Get user's IP address and hostname
    $userIP = $_SERVER['REMOTE_ADDR'];
    $userHostname = gethostbyaddr($userIP);

    // Update total hit count
    $totalHits = updateHitCount($hitCountFile);

    // Update user's hit count
    $userKey = $userIP . '-' . $userHostname;
    $userHits = updateUserHitCount('hitcounter/userhits_' . $key . '.txt', $userKey);

    // Prepare JSON response
    $response = [
        'totalHits' => $totalHits,
        'userHits' => $userHits,
        'status' => "ok",
        'ec' => 200
    ];
}

// Output JSON response
header('Content-Type: application/json');
echo json_encode($response);

?>
